name: Telegram Bridge

on:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened, edited, closed, reopened ]
  pull_request:
    types: [ opened, ready_for_review, review_requested, reopened ]
  push:

jobs:
  build:
    name: Telegram Bridge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify about issue comment
        if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 🗣 Комментарий от @${{ github.event.comment.user.login }} в [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) - ${{ github.event.comment.body }}
          
      - name: Notify about new issue
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 👾 Задач привалило - [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) от @${{ github.event.issue.user.login }}
          
      - name: Notify about issue closed
        if: ${{ github.event_name == 'issues' && github.event.action == 'closed'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ✅ Задача закрыта - [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
          
      - name: Notify about issue reopen
        if: ${{ github.event_name == 'issues' && github.event.action == 'reopened'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ♻️ Что-то не доделали в задаче, снова открыта - [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
          
      - name: Notify about PR open
        if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 🛠 @${{ github.event.pull_request.user.login}} прислал новый PR - [${{ github.event.pull_request.title}}](${{ github.event.pull_request.html_url}})
          
      - name: Notify about PR ready for review
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'ready_for_review'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ✅ PR [${{ github.event.pull_request.title}}](${{ github.event.pull_request.html_url}}) готов к просмотру
          
      - name: Notify about PR open
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'review_requested'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
          ❗️Требуется ревью для PR: - [${{ github.event.pull_request.title}}](${{ github.event.pull_request.html_url}})
          
      - name: Notify about push in main
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 💚 Пуш в мастере от @${{ github.event.head_commit.author.username}} - [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url}}
