name: telegram message
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  telegram:
    name: telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ⚡️ ${{ github.actor }} сделал коммит:

            ```
            ${{ github.event.commits[0].message }}
            ```

            Изменения: ![Ссылка](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Репозиторий: ![${{ github.repository }}](https://github.com/${{ github.repository }})
