name: telegram message
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  telegram:
    name: telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ⚡️ ${{ github.actor }} сделал коммит:
            \`\`\`
            ${{ github.event.commits[0].message }}
            \`\`\`
            
            Изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Репозиторий: https://github.com/${{ github.repository }}
