name: telegram message
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  telegram:
    name: telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
<<<<<<< HEAD
		  format: markdown
=======
          format: markdown
>>>>>>> 3b0dac9 (change on markdown v2)
          message: |
            ⚡️ ${{ github.actor }} сделал коммит:

            ```python
            pre-formatted fixed-width code block written in the Python programming language
            ```
            
            ${{ github.event.commits[0].message }}
<<<<<<< HEAD
            
            Изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Репозиторий: https://github.com/${{ github.repository }}
=======
            ```

            Изменения: ![Ссылка](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Репозиторий: ![${{ github.repository }}](https://github.com/${{ github.repository }})
>>>>>>> 3b0dac9 (change on markdown v2)
